apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: gimbal-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: gimbal-monitoring
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: prometheus
  namespace: gimbal-monitoring
spec:
  ports:
  - protocol: TCP
    name: prometheus
    port: 9090
  - protocol: TCP
    name: alertmanager
    port: 9093
  selector:
    app: prometheus
    component: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: gimbal-monitoring
  labels:
    app: prometheus
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: server
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        component: server
    spec:
      nodeSelector:
        workload: contour
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.2.1
        imagePullPolicy: Always
        args:
          - '--storage.tsdb.retention=24h'
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: cert-file
          mountPath: /etc/ssl/etcd.pem
        - name: key-file
          mountPath: /etc/ssl/etcd-key.pem
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: cert-file
        hostPath:
          path: /etc/kubernetes/ssl/etcd.pem
      - name: key-file
        hostPath:
          path: /etc/kubernetes/ssl/etcd-key.pem