apiVersion: v1
kind: Service
metadata:
 name: iperf3-server
 namespace: default
spec:
 ports:
 - port: 5201
   protocol: TCP
   targetPort: 5201
 selector:
   app: iperf3-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: iperf3-server
 labels:
   app: iperf3-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app: iperf3-server
 template:
   metadata:
     labels:
       app: iperf3-server
   spec:
     nodeSelector:
       workload: envoy
     containers:
     - name: iperf3-server
       image: networkstatic/iperf3
       args: ['-s']
     terminationGracePeriodSeconds: 5