apiVersion: v1
kind: Pod
metadata:
 name: iperf3-client
spec:
 containers:
 - name: iperf3-client
   image: networkstatic/iperf3
   command:
   - iperf3
   - -t
   - "60"
   - -c
   - iperf3-server
 terminationGracePeriodSeconds: 5
 restartPolicy: Never
 nodeSelector:
   workload: wrk