apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nginx
  namespace: default
  labels:
    test: batch
spec:
  virtualhost:
    fqdn: example.com
  routes:
  - services:
    - name: nginx
      port: 80